#!/bin/sh /etc/rc.common                                                        
# Copyright (C) 2006 OpenWrt.org                                                
                                                                                
START=11                                                                        
start() {                                                                       
    mkdir /tmp/new
    if [ ! -e /dev/sda1 ]; then
        echo "/dev/sda1 not found, skip usb boot"
        exit
    fi
    mount /dev/sda1 /tmp/new
    if [ ! -f /tmp/new/linux.elf ]; then
        echo "linux.elf not found, skip usb boot"
        exit
    fi
    kexec -l /tmp/new/linux.elf --command-line="board=TL-WR720N console=ttyATH0,115200"
    #Set the watchdog, so that the booting should complete before the watchdog restarts the system
    killall watchdog
    watchdog -T 300 -t 30 /dev/watchdog
    kexec -e
}