adb push static/jquery.js /sdcard/manager/static/jquery.js
adb push static/jquery.mobile.js /sdcard/manager/static/jquery.mobile.js
adb push static/jquery.mobile.css /sdcard/manager/static/jquery.mobile.css
adb push static/images/ajax-loader.gif /sdcard/manager/static/images/ajax-loader.gif
adb push static/images/icons-18-black.png /sdcard/manager/static/images/icons-18-black.png
adb push static/images/icons-18-white.png /sdcard/manager/static/images/icons-18-white.png
adb push static/images/icons-36-black.png /sdcard/manager/static/images/icons-36-black.png
adb push static/images/icons-36-white.png /sdcard/manager/static/images/icons-36-white.png
adb push delegated-apnic-latest.txt /sdcard/manager/delegated-apnic-latest.txt
