#!/usr/bin/lua
require 'uci'

x = uci.cursor()
function exit_if_sta_mode_wifi_interface_enabled(section)
	if 'sta' == section.mode and '0' == section.disabled then
		os.execute('logger -s -t fqrouter std mod wifi interface ' .. section.ssid .. ' already enabled')
		os.exit()
	end
end
x:foreach('wireless', 'wifi-iface', exit_if_sta_mode_wifi_interface_enabled)
os.execute('logger -s -t fqrouter no sta mode wifi interface enabled')

function is_wlan0_up()
    local f = assert(io.popen('ifconfig wlan0', 'r'))
    local output = assert(f:read('*a'))
    return output:find('RUNNING')
end
for count=1,10 do
    if is_wlan0_up() then
        break
    end
    os.execute('sleep 1')
end
if not is_wlan0_up() then
    os.execute('logger -s -t fqrouter wlan0 not up in given time')
    os.exit()
end
os.execute('logger -s -t fqrouter wlan0 is up')

local f = assert(io.popen('iw dev wlan0 scan | grep SSID', 'r'))
local accessPoints = assert(f:read('*a'))
f:close()
os.execute('logger -s -t fqrouter "access points: ' .. accessPoints .. '"')
function enable_sta_mode_wifi_interface(section)
	if 'sta' == section.mode and accessPoints:find(section.ssid, nil, true) then
		os.execute('logger -s -t fqrouter found ' .. section.ssid)
		x:set('wireless', section['.name'], 'disabled', 0)
		x:commit('wireless')
		os.execute('touch /tmp/skip-only-enable-connectable-sta-mode-wifi-interface')
		os.execute('wifi up')
		os.execute('rm /tmp/skip-only-enable-connectable-sta-mode-wifi-interface')
		os.exit()
	end
end
x:foreach('wireless', 'wifi-iface', enable_sta_mode_wifi_interface)
