#!/bin/sh /etc/rc.common                                                        
# Copyright (C) 2006 OpenWrt.org                                                
                                                                                
START=11
d() {
    echo $1 > /dev/null
}
mount_usb() {
    for disk in $(find /dev/sd*)
    do
        d $(mount $disk /tmp/usb_boot 2>&1)
        if [ -f /tmp/usb_boot/fqrouter/boot ] ; then
            echo "found fqrouter in $disk"
            return
        fi
        d $(umount /tmp/usb_boot 2>&1)
    done
}
start() {
    mkdir /tmp/usb_boot
    mount_usb
    if [ ! -f /tmp/usb_boot/fqrouter/boot ] ; then
        echo 'skip usb boot due to the boot file not found'
        exit
    fi
    . /tmp/usb_boot/fqrouter/boot
    echo "fqrouter version: $FQROUTER_VERSION"
    echo "kernel command line: $KERNEL_COMMAND_LINE"
    if [ ! -f /tmp/usb_boot/fqrouter/$FQROUTER_VERSION.initramfs ] ; then
        echo 'skip sub boot due to initramfs not found'
        exit
    fi
    if [ -n "$KERNEL_COMMAND_LINE" ] ; then
        kexec -l /tmp/usb_boot/fqrouter/$FQROUTER_VERSION.initramfs --command-line="$KERNEL_COMMAND_LINE"
    else
        echo 'no kernel command line might not boot'
        kexec -l /tmp/usb_boot/fqrouter/$FQROUTER_VERSION.initramfs
    fi
    #Set the watchdog, so that the booting should complete before the watchdog restarts the system
    killall watchdog
    watchdog -T 300 -t 30 /dev/watchdog
    kexec -e
}
